import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Q,compileTiming,validatePlan} from '../assets/motion-code/contract.mjs';
import {compileLayout,wrapLabel} from '../assets/motion-code/layout.mjs';
import {layerState,sceneState} from '../assets/motion-code/src/state.mjs';
import {exportProject,exportOptions,placements,exactFpsArgs} from '../assets/motion-code/export.mjs';
import {readJson,writeJson,resolveSettings,prepareProject,attachProject,saveConfig,loadConfig,skillRoot} from '../scripts/core.mjs';
import {startGallery} from '../scripts/gallery.mjs';
import {inputs,requireFresh} from '../assets/motion-code/project.mjs';
import {hash} from '../assets/motion-code/io.mjs';
import {spawnSync} from 'node:child_process';
const here=path.dirname(fileURLToPath(import.meta.url)),fixture=n=>readJson(path.join(here,'fixtures',n));
const catalog=readJson(path.join(skillRoot,'styles/catalog.json')),settings=()=>resolveSettings({},readJson(path.join(skillRoot,'config/defaults.json')));
const measure=(text,size)=>text.length*size*.5,layout=(p=fixture('mountain-plan.json'),s=settings(),source={words:[]})=>compileLayout(p,source,s,catalog,measure);
const temp=t=>{const p=fs.mkdtempSync(path.join(os.tmpdir(),'motion-test-'));t.after(()=>fs.rmSync(p,{recursive:true,force:true}));return p;};
const plugin=()=>({availableInApp:true,instructionPath:path.join(skillRoot,'tests/fixtures/plugin.md'),checkedAt:new Date().toISOString()});
test('single-style registry exposes exactly the five implemented components',()=>{assert.equal(catalog.length,1);assert.equal(Object.keys(catalog[0].components).length,5);assert.throws(()=>validatePlan({...fixture('mountain-plan.json'),style:'unknown'},{words:[]},settings(),catalog),/Unsupported style/);});
test('exact fractional frames and half-up boundaries reject rounded fps',()=>{assert.equal(Q(500,'30000/1001'),15);assert.equal(Q(250,'30/1'),8);assert.equal(Q(1001,'30000/1001'),30);assert.throws(()=>Q(100,'29.97'),/exact/);assert.throws(()=>Q(-1,'30/1'),/Negative/);});
test('plan arithmetic fixture preserves word occurrences and both placements',()=>{
 const s={startMs:10000,endMs:14500,exitStartMs:14250,motion:{entranceMs:250,exitMs:250},events:[{id:'first',anchorWord:4,durationMs:500},{id:'second',anchorWord:8,durationMs:500}]};
 const source={words:Array.from({length:10},(_,i)=>({text:i%2?'units':'in',startMs:i===4?10250:12000}))};
 const f=compileTiming(s,source,{...settings(),sourceOffsetMs:500,timelinePlacementMs:10000});
 assert.deepEqual([f.start,f.end,f.duration,f.placementFrame],[315,450,135,615]);assert.deepEqual(f.events.map(e=>e.localFrame),[8,60]);assert.equal(f.localExit,128);assert.equal(f.events[0].frame+f.editorOrigin,623);assert.equal(f.events[1].localComplete,75);
});
test('handles preserve animation origin and reject a negative file origin',()=>{const s=layout().scenes[0];assert.throws(()=>compileTiming({...s,handles:{leadingMs:100,trailingMs:100}},{},settings()),/Negative/);const f=compileTiming({...s,startMs:1000,endMs:4500,exitStartMs:4250,handles:{leadingMs:100,trailingMs:200}},{},{...settings()});assert.equal(f.localStart,3);assert.equal(f.duration,114);});
test('missing timestamps retain untimed transcript planning and never become standalone',()=>{const p=fixture('preview-plan.json'),source=fixture('preview-source.json');delete source.words[0].startMs;const r=validatePlan(p,source,settings(),catalog);assert.equal(r.status,'needs-word-timing');assert.throws(()=>layout(p,settings(),source),/timestamps/);});
test('invalid word ranges, anchors, overrides, missing assets and modes fail early',()=>{
 const base=fixture('preview-plan.json'),source=fixture('preview-source.json');
 for(const mutate of [p=>p.graphicsPlan.scenes[0].sourceRanges=[[0,999]],p=>p.graphicsPlan.scenes[0].anchorWord=1,p=>p.authoredOverrides.project={banana:true},p=>p.graphicsPlan.scenes[0].layers[0].asset='absent',p=>p.graphicsPlan.scenes[0].background='#FFFFFF']){const p=structuredClone(base);mutate(p);assert.throws(()=>validatePlan(p,source,settings(),catalog));}
});
test('parallax moves near/far differently and shuffled seeks are deterministic',()=>{const s=layout().scenes[0],end=s.frames.exitStart;const x=s.layers.map(l=>layerState(s,l,end).x);assert.deepEqual(x,[12,30,60]);const frames=[0,20,80,50,104];const expected=new Map(frames.map(f=>[f,s.layers.map(l=>layerState(s,l,f))]));for(const f of [104,0,50,20,80])assert.deepEqual(s.layers.map(l=>layerState(s,l,f)),expected.get(f));assert.equal(sceneState(s,-1).active,false);assert.equal(sceneState(s,105).active,false);assert.equal(sceneState(s,40).opacity,1);});
test('coverage, protected tracks and geometry reject unsafe plans',()=>{const p=fixture('mountain-plan.json');p.graphicsPlan.scenes[0].layers[0].rect={x:0,y:0,width:820,height:600};assert.throws(()=>layout(p),/coverage/);assert.throws(()=>layout(undefined,{...settings(),exclusions:[{x:300,y:800,width:100,height:100,space:'design'}]}),/protected/);assert.doesNotThrow(()=>layout(undefined,{...settings(),exclusions:[{x:300,y:800,width:100,height:100,space:'design',startMs:5000,endMs:6000}]}));});
test('label reflow precedes shrink; impossible labels fail; fast scenes fail',()=>{const l=wrapLabel('This label wraps across lines',320,48,measure);assert.equal(l.fontSize,48);assert.ok(l.lines.length>1);assert.throws(()=>wrapLabel('X'.repeat(200),300,48,measure),/36px/);const p=fixture('diagram-plan.json');p.graphicsPlan.scenes[0].endMs=800;assert.throws(()=>layout(p),/reading hold/);});
test('preview scenes have sparse gaps, optional materials and explicit full-screen only',()=>{const g=layout(fixture('preview-plan.json'),settings(),fixture('preview-source.json'));assert.equal(g.scenes.length,4);assert.ok(g.scenes.every(s=>!sceneState(s,150).active));assert.equal(g.scenes[0].content,undefined);assert.equal(g.scenes[1].sourceLabel,undefined);assert.equal(g.scenes[2].fibers.length,160);const p=fixture('mountain-plan.json');p.graphicsPlan.scenes[0].sceneMode='full-screen';p.graphicsPlan.scenes[0].background='#202124';assert.equal(layout(p).scenes[0].background,'#202124');});
test('config merges export roles, freezes preparation and resumes same path',t=>{const dir=temp(t),config=path.join(dir,'config.json');saveConfig({projectFolder:dir,export:{scale:1}},config);assert.equal(loadConfig(config).export.profile,'4444');const run={plugin:plugin(),projectName:'test',planPath:path.join(here,'fixtures/mountain-plan.json')};const prepared=prepareProject(run,{saved:loadConfig(config),checkRuntime:()=>({})});fs.mkdirSync(prepared.projectPath);const retry=prepareProject(prepared,{saved:{...settings(),width:720},checkRuntime:()=>({})});assert.equal(retry.projectPath,prepared.projectPath);assert.equal(retry.prepared.settings.width,1080);const collision=prepareProject(run,{saved:loadConfig(config),checkRuntime:()=>({})});assert.notEqual(collision.projectPath,prepared.projectPath);});
test('attachment retries matching partial files and never overwrites completed user edits',t=>{const dir=temp(t),run=prepareProject({plugin:plugin(),projectName:'test',planPath:path.join(here,'fixtures/mountain-plan.json')},{saved:{...settings(),projectFolder:dir},checkRuntime:()=>({})});fs.mkdirSync(run.projectPath);writeJson(path.join(run.projectPath,'package.json'),{dependencies:{remotion:'4.0.526'}});attachProject(run);const code=path.join(run.projectPath,'motion/src/state.mjs');fs.appendFileSync(code,'\n// user edit');attachProject(run);assert.match(fs.readFileSync(code,'utf8'),/user edit/);assert.ok(fs.existsSync(path.join(run.projectPath,'public/assets/car.svg')));});
test('export options and manifests preserve alpha dimensions and mode arithmetic',()=>{const p={settings:settings(),graphicsPlan:layout(),fingerprint:'test'};assert.deepEqual(exportOptions(p.settings),{codec:'prores',proResProfile:'4444',pixelFormat:'yuva444p10le',imageFormat:'png',muted:true,scale:2});const a=placements(p,'clips'),b=placements(p,'sequence');assert.equal(a.scenes[0].placementFrame,b.scenes[0].placementFrame);assert.equal(a.exported.height,3840);});
test('failed export keeps progress; retries reuse hashes; conflicting files stay intact',async t=>{const root=temp(t),g=layout(fixture('preview-plan.json'),settings(),fixture('preview-source.json')),p={settings:settings(),graphicsPlan:g,fingerprint:'a',compiledHash:'a'};let calls=0;await assert.rejects(exportProject(root,p,async({outputLocation})=>{calls++;if(calls===2)throw Error('encoder failed');fs.writeFileSync(outputLocation,'valid-first');}),/encoder/);assert.ok(!fs.existsSync(path.join(root,'out/placement-manifest.json')));let retries=0;await exportProject(root,p,async({outputLocation})=>{retries++;fs.writeFileSync(outputLocation,'encoded');});assert.equal(retries,3);await exportProject(root,p,async()=>assert.fail('must reuse'));const file=path.join(root,'out/spark.mov');fs.writeFileSync(file,'user edit');await assert.rejects(exportProject(root,p,async()=>{}),/Conflicting output/);assert.equal(fs.readFileSync(file,'utf8'),'user edit');});
test('gallery token/origin validation and Save continuation preserve run state',async t=>{const dir=temp(t),file=path.join(dir,'run.json');writeJson(file,{projectName:'kept'});let event;const {server,url}=await startGallery(file,{onSelection:e=>event=e});t.after(()=>server.close());assert.equal((await fetch(url.split('?')[0])).status,403);const select=new URL(url);select.pathname='/select';const response=await fetch(select,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({style:catalog[0].id,colors:catalog[0].colors})});assert.equal(response.status,200);assert.equal(readJson(file).colorsAccepted,true);assert.equal(readJson(file).projectName,'kept');assert.equal(event.event,'selection-saved');});
test('source, assets, code and settings invalidate compilation; snapshot tampering fails',t=>{
 const dir=temp(t),run=prepareProject({plugin:plugin(),projectName:'freshness',planPath:path.join(here,'fixtures/mountain-plan.json')},{saved:{...settings(),projectFolder:dir},checkRuntime:()=>({})});fs.mkdirSync(run.projectPath);writeJson(path.join(run.projectPath,'package.json'),{dependencies:{remotion:'4.0.526'}});attachProject(run);writeJson(path.join(run.projectPath,'package-lock.json'),{lockfileVersion:3});
 const data=inputs(run.projectPath),graphicsPlan=layout(),p={fingerprint:data.fingerprint,graphicsPlan,compiledHash:hash(graphicsPlan)};writeJson(path.join(run.projectPath,'project.json'),p);writeJson(path.join(run.projectPath,'compiled-motion.json'),p);assert.doesNotThrow(()=>requireFresh(run.projectPath));
 for(const name of ['settings.json','source.json','motion/src/state.mjs','public/assets/car.svg']){const file=path.join(run.projectPath,name),original=fs.readFileSync(file);if(name.endsWith('.json')){const j=readJson(file);j.changed=true;writeJson(file,j);}else fs.appendFileSync(file,'\n');assert.throws(()=>requireFresh(run.projectPath),/Stale/);fs.writeFileSync(file,original);}
 writeJson(path.join(run.projectPath,'compiled-motion.json'),{});assert.throws(()=>requireFresh(run.projectPath),/snapshot/);
});
test('partial attachment recovers known files and rejects unknown collisions',t=>{
 const dir=temp(t),run=prepareProject({plugin:plugin(),projectName:'partial',planPath:path.join(here,'fixtures/mountain-plan.json')},{saved:{...settings(),projectFolder:dir},checkRuntime:()=>({})});fs.mkdirSync(run.projectPath);writeJson(path.join(run.projectPath,'package.json'),{dependencies:{remotion:'4.0.526'}});attachProject(run);
 const journal=path.join(run.projectPath,'.motion-attachment.json'),state=readJson(journal);state.complete=false;writeJson(journal,state);fs.unlinkSync(path.join(run.projectPath,'motion/export.mjs'));attachProject(run);assert.ok(fs.existsSync(path.join(run.projectPath,'motion/export.mjs')));
 state.complete=false;writeJson(journal,state);fs.appendFileSync(path.join(run.projectPath,'motion/export.mjs'),'// manually changed');assert.throws(()=>attachProject(run),/Conflicting file/);
});
test('isolated installation loads defaults and validates without captions',t=>{
 const dir=temp(t),installed=path.join(dir,'motion-graphics');fs.cpSync(skillRoot,installed,{recursive:true});const cli=path.join(installed,'scripts/motion-graphics.mjs');const result=spawnSync(process.execPath,[cli,'defaults'],{cwd:dir,encoding:'utf8'});assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).export.scale,2);assert.equal(fs.existsSync(path.join(dir,'captions')),false);
 const isolated=spawnSync(process.execPath,['--input-type=module','-e',`import {validatePlan} from './motion-graphics/assets/motion-code/contract.mjs'; import {readJson,resolveSettings} from './motion-graphics/scripts/core.mjs'; console.log(validatePlan(readJson('./motion-graphics/tests/fixtures/mountain-plan.json'),{words:[]},resolveSettings({},readJson('./motion-graphics/config/defaults.json')),readJson('./motion-graphics/styles/catalog.json')).status)`],{cwd:dir,encoding:'utf8'});assert.equal(isolated.status,0,isolated.stderr);assert.match(isolated.stdout,/validated/);
});

test('encoder receives exact saved fractional rate without altering other arguments',()=>{assert.deepEqual(exactFpsArgs(['-r','29.97002997002997','-i','frame-%d.png','-pix_fmt','yuva444p10le'],'30000/1001'),['-r','30000/1001','-i','frame-%d.png','-pix_fmt','yuva444p10le']);});
test('colliding labels, duplicate events and pending picker saves cannot proceed',()=>{const p=fixture('preview-plan.json');p.graphicsPlan.scenes[3].annotations.push({...p.graphicsPlan.scenes[3].annotations[0],label:'Collision'});assert.throws(()=>layout(p,settings(),fixture('preview-source.json')),/collision/);const s=fixture('mountain-plan.json');s.graphicsPlan.scenes[0].events=[{id:'same',timeMs:500},{id:'same',timeMs:700}];assert.throws(()=>layout(s),/Unique event/);assert.throws(()=>prepareProject({plugin:plugin(),prepared:{},projectPath:'existing',pickerOpened:true,colorsAccepted:false},{checkRuntime:()=>({})}),/picker Save/);});
