// Additional actual-component checks, using the project reported by editorial-render-check.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {readJson,skillRoot,resolveSettings,loadConfig} from '../scripts/core.mjs';
const project=path.resolve(process.argv[2]);
process.chdir(project);
const fromRuntime=relative=>import(pathToFileURL(path.join(project,'node_modules',relative)));
const {bundle}=await fromRuntime('@remotion/bundler/dist/index.js');
const {renderFrames,renderStill,selectComposition}=await fromRuntime('@remotion/renderer/dist/index.js');
fs.copyFileSync(path.join(skillRoot,'styles/active-word-highlight/fonts/Inter-Bold.woff2'),path.join(project,'public/fonts/Inter-Bold.woff2'));
const serveUrl=await bundle({entryPoint:path.join(project,'src/captions/index.tsx'),publicDir:path.join(project,'public')});
const composition=await selectComposition({serveUrl,id:'Captions'});
const props=readJson(path.join(project,'project.json'));
let sequential;
await renderFrames({serveUrl,composition,inputProps:props,outputDir:null,imageFormat:'png',frameRange:[9,34],concurrency:1,onStart:()=>{},onFrameUpdate:()=>{},onFrameBuffer:(buffer,frame)=>{if(frame===34)sequential=buffer;}});
assert.ok(sequential.equals(fs.readFileSync(path.join(project,'seek-34.png'))),'Sequential playback and arbitrary seek differ');
const words=(text,start=0,step=40)=>text.split(' ').map((text,i)=>({text:`${i?' ':''}${text}`,startMs:start+i*step,endMs:start+(i+1)*step,timestampMs:null,confidence:null}));
const fast={...props,settings:{...props.settings,styleOptions:{phrases:{0:{groupSizes:[1,1,1],underline:'orange'}}}},sentences:[{words:words('Go go go!')},{words:words('Then stop',120)}]};
for(const frame of [1,2,3,4,5,8])await renderStill({serveUrl,composition:{...composition,props:fast},inputProps:fast,frame,output:path.join(project,`fast-${frame}.png`),imageFormat:'png'});
const long={...props,settings:{...props.settings,styleOptions:{sizes:{primary:80}}},sentences:[{words:words('Wiedererkennungsmerkmal',0,1000)}]};
await renderStill({serveUrl,composition:{...composition,props:long},inputProps:long,frame:15,output:path.join(project,'long-word.png'),imageFormat:'png'});
const tooLong={...long,sentences:[{words:words('x'.repeat(100),0,1000)}]};
await assert.rejects(()=>renderStill({serveUrl,composition:{...composition,props:tooLong},inputProps:tooLong,frame:15,output:path.join(project,'invalid.png'),imageFormat:'png'}),/safe width/);
const activeSettings=resolveSettings({style:'active-word-highlight',colorsAccepted:true},loadConfig());
const active={...readJson(path.join(skillRoot,'tests/fixtures/normalized.json')),settings:{...activeSettings,durationInFrames:88}};
await renderStill({serveUrl,composition:{...composition,props:active},inputProps:active,frame:20,output:path.join(project,'active-regression.png'),imageFormat:'png'});
console.log('Actual component: sequential/seek equality, fast/repeated/adjacent phrases, long-word fitting/rejection and existing-style render passed');
